# #TODO일단은 인스턴스 확정되면 주석을 푸시오

# name: Deploy to AWS EC2

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Deploy to EC2
#         uses: appleboy/ssh-action@v0.1.10
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ secrets.EC2_USERNAME }}
#           key: ${{ secrets.EC2_SSH_KEY }}
#           script: |
#             # 서버`에 접속하자마자 수행될 명령어들입니다.
#             # 1. 코드가 다운받아질 위치로 이동합니다. (본인의 EC2 경로에 맞게 수정!)
#             # 예: cd ~/maratang-server
#             cd ~/demo-repository
            
#             # 2. GitHub에서 최신 코드를 다운받습니다.
#             git pull origin main
            
#             # 3. 기존 컨테이너 중단 및 새 이미지 파이프라인으로 다시 띄웁니다.
#             sudo sh ./start_prod.sh
